# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5444abecd8c9ce5d0683bfee4874a444ccce3b57457225de6d32f02087b494ae8e0e7482c1f9420e3aa7abb8ff9b67cbd15e72c52e2d7427722a436b576c8128

test:
  secret_key_base: 975ed15ad45b0288d913b26d864de26e9ded99fdf30cfb61f20a8acc8133bd1fe8b3ec8d26f7ad44bfc003e2cd1ddb5c5640d0bb144238d79b328e0381972ff7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
